# Generated by Django 5.1.5 on 2025-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrearTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=100)),
                ('descrip_tarea', models.CharField(max_length=250)),
                ('fechaLim_tarea', models.DateField(verbose_name='Fecha de publicacion')),
            ],
        ),
    ]
